# -*- coding: utf-8 -*-
"""prak9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OW68e1vIPD-RYrfhrSan-Rg9j_wRnBbX
"""

print('@@@@      @     @@@@ @     @')
print('@  @     @ @    @    @     ')
print('@ @     @   @   @@@@ @     @  ')
print('@  @   @ @@@ @  @    @     @   ')
print('@   @ @       @ @    @@@@@ @      ')
def konversi_list_ke_tuple(daftar):
    return tuple(daftar)
input_list = input("Masukkan angka: ")
list_input = input_list.split()
tuple_hasil = konversi_list_ke_tuple(list_input)
print("List:", list_input)
print("Tuple:", tuple_hasil)

print('@@@@      @     @@@@ @     @')
print('@  @     @ @    @    @     ')
print('@ @     @   @   @@@@ @     @  ')
print('@  @   @ @@@ @  @    @     @   ')
print('@   @ @       @ @    @@@@@ @      ')
R = ('1021, 1022, 1023', '1025, 1026, 1027', '1029, 1030, 1030')
print(R)
def rata_rata(angka):
    rata_rata = [int(x) for x in angka.split(', ')]
    return int(sum(rata_rata) / len(rata_rata))

averages = [rata_rata(group) for group in R]
print(f"rata rata dari tuple adalah : {averages} ")
print("====MUHAMMAD RAFLI ILHAM FAHROZI=====")
print("=========064002300006================")

print('@@@@      @     @@@@ @     @')
print('@  @     @ @    @    @     ')
print('@ @     @   @   @@@@ @     @  ')
print('@  @   @ @@@ @  @    @     @   ')
print('@   @ @       @ @    @@@@@ @      ')
R = [1,2,4,3]
print(R)
hasil = 1
for result in R:
    hasil *= result
print(hasil)

print('@@@@      @     @@@@ @     @')
print('@  @     @ @    @    @     ')
print('@ @     @   @   @@@@ @     @  ')
print('@  @   @ @@@ @  @    @     @   ')
print('@   @ @       @ @    @@@@@ @      ')
def hitung_string_cocok(list_string):
    jumlah_cocok = 0

    for string in list_string:
        if len(string) >= 2 and string[0] == string[-1]:
            jumlah_cocok += 1
    return jumlah_cocok

# Contoh penggunaan:
daftar_string = ['bang gaga', 'dan', 'bang natan', 'terkeren']
jumlah = hitung_string_cocok(daftar_string)
print("list kata:",daftar_string)
print(f"Jumlah string dengan karakter pertama dan terakhir sama adalah: {jumlah}")